# Default values for admission-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: authz-sample

json_values: {
  "deployment":{
    "registry": "acrbackstagedev1.azurecr.io",
    "image_sample": "sample-authz:0.0.1",
    "name": "sample-authz",
    "bundle_name": "sample-authz.tar.gz",
    "port": 8080
  },
  build_values: {
    "golang":{
      "goos": "linux",
      "goarch": "amd64"
    }
  }
}

secret_cfg_sa:
  name: sample-authz-cfg-sa
  value: |
    STORAGE_ACCOUNT="sabundle" 
    TENANT_ID='4cb367c8-fd7f-41de-8d1b-871bc2c81157' 
    CLIENT_ID='a628b563-17bc-47de-b20f-12ccbd6b399d' 
    SECRET='QZp8Q~KcqaCSJ-a7tbvtebu40ac96lKL125Edbfp' 
    CONTAINER_NAME='bundle' 

 
docker:
  platform: linux/amd64
  docker_cfg_json: {
    "auths": {
      "acrbackstagedev1.azurecr.io": {
        "username": "acrbackstagedev1",
        "password": "BmzJqxgLHOt8ys1ZOxDJ/K6QO5ncxhisB3zseSGhvY+ACRAF/lVF",
        "auth": "YWNyYmFja3N0YWdlZGV2MTpCbXpKcXhnTEhPdDh5czFaT3hESi9LNlFPNW5jeGhpc0IzenNlU0dodlkrQUNSQUYvbFZG"
      }
    }
  }