apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp2
  name: testapp2
  namespace: authz-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testapp2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        opa-bundle-name: bundle.tar.gz
        opa-cfg-file: storage-account-secret-file
        opa-enabled: "true"
      creationTimestamp: null
      labels:
        app: testapp2
      name: testapp2
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      initContainers:
      - image: busybox
        imagePullPolicy: Always
        name: busy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
