apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.json_values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.json_values.deployment.name }}
spec:
  ports:
    - port: {{ .Values.json_values.deployment.port }}
      name: http
  selector:
    app: {{ .Values.json_values.deployment.name }}
