apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authz-secret-reader-role-binding
subjects:
- kind: ServiceAccount
  name: default  
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: authz-secret-reader-role
  apiGroup: rbac.authorization.k8s.io