apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authz-secret-reader-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list"]
 