apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.json_values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.json_values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.json_values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.json_values.deployment.name }}
      name: {{ .Values.json_values.deployment.name }}
    spec:
      containers:
        - image: {{ (list .Values.json_values.deployment.registry .Values.json_values.deployment.image_admission_ctrl | join "/") }} 
          name: {{ .Values.json_values.deployment.name }}
          ports:
          - containerPort: 443
          imagePullPolicy: Always
          env:
            - name: PROXY_IMAGE
              value: {{ (list .Values.json_values.deployment.registry .Values.json_values.deployment.image_proxy | join "/") }}  
            - name: OPA_IMAGE
              value: {{ (list .Values.json_values.deployment.registry .Values.json_values.deployment.image_opa | join "/") }}   
            - name: PROXY_INIT
              value: {{ (list .Values.json_values.deployment.registry .Values.json_values.deployment.image_init | join "/") }} 
          volumeMounts:
            - mountPath: /app/cert/
              name: tls-admission-crtl
              readOnly: true
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: tls-admission-crtl
          secret:
            defaultMode: 420
            secretName: tls-admission-crtl          
 

