apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admission-controller-inject
  namespace: {{ .Values.namespace }}
  name: admission-controller-inject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller-inject
  template:
    metadata:
      labels:
        app: admission-controller-inject
      name: admission-controller-inject
    spec:
      containers:
        - image:  {{ .Values.json_values.deployment.image_admission_ctrl }}
          name: admission-controller-inject
          ports:
          - containerPort: 443
          imagePullPolicy: Always
          env:
            - name: PROXY_IMAGE
              value: {{ .Values.json_values.deployment.image_proxy }}
            - name: OPA_IMAGE
              value: {{ .Values.json_values.deployment.image_opa }}
            - name: PROXY_INIT
              value: {{ .Values.json_values.deployment.image_init }}
      imagePullSecrets:
      - name: regcred           
       
---
apiVersion: v1
kind: Service
metadata:
  name: admission-controller-inject
  namespace: {{ .Values.namespace }}
  labels:
    app: admission-controller-inject
spec:
  ports:
    - port: 443
      name: https
  selector:
    app: admission-controller-inject
