apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: authz-webhook-admission-controller
webhooks:
  - name: auth.basajuan.io
    clientConfig:
      service:
        name: {{ .Values.json_values.deployment.name }}
        namespace: {{ .Release.Namespace }}
        path: "/mutation"
      caBundle: '{{ .Values.cert.ca_crt | b64enc }}'
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        authz-system: enabled
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1beta1

