apiVersion: v1
data:
  cert.crt: {{ .Values.cert.admision_controller.crt | b64enc }}
  cert.key: {{ .Values.cert.admision_controller.key | b64enc }}
kind: Secret
metadata:  
  name: tls-admission-crtl 
  namespace: {{ .Release.Namespace }}
